apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
        - name: DB_HOST
          value: "booksdb-postgres.postgres.database.azure.com"
        - name: DB_NAME
          value: "booktracker_db"
        - name: DB_USER
          value: "adminuser"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_PORT
          value: "5432"