name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Start Docker
      run: docker compose up -d --build #run in detached mode so the workflow can continue to subsequent test steps

    - name: Wait for API to start #allow fastapi and postgresql time to initialise before testing
      run: sleep 10

    - name: Show running containers
      run: docker compose ps

    - name: Check health endpoint status
      run: curl --fail http://localhost:8000/health

    - name: Check books endpoint status
      run: curl --fail http://localhost:8000/books

    - name: Show Docker logs if fail
      if: failure()
      run: docker compose logs

    - name: Shutdown Docker
      if: always()
      run: docker compose down #clean up containers even if a previous step fails

      #only proceed to azure if docker succeeds
      #only proceed on push
    - name: Log in to Azure
      uses: azure/login@v2
      if: github.event_name=='push'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      if: github.event_name=='push'
      run: az acr login --name booksdb

    - name: Build image
      if: github.event_name=='push'
      run: docker build -t booksdb.azurecr.io/booksdb:latest .

    - name: Push image
      if: github.event_name=='push'
      run: docker push booksdb.azurecr.io/booksdb:latest