name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Start Docker
      run: docker compose up -d --build #run in detached mode so there's no need to detach it from the frontend

    - name: Check health endpoint status
      run: curl --fail http://localhost:8000/health

    - name: Check books endpoint status
      run: curl --fail http://localhost:8000/books

    - name: Shutdown Docker
      if: always()
      run: docker compose down #composes down even if tests fail